version: "3.8"

services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=10240M
      - PHP_UPLOAD_LIMIT=10240M
      - PHP_MEMORY_LIMIT=2048M
      - POSTGRES_HOST=db  # HERE
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    volumes:
      - nextcloud:/var/www/html

  db:
    image: postgres:latest
    restart: unless-stopped
    hostname: 'db'  # AND HERE
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  nextcloud:
    name: nextcloud
  db:
    name: db
